xlsynth/topstitch

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
`slang-rs` from this organization is used for Verilog parsing in `from_verilog`
Tieoffs make use of the new binding for arbitrary-size literals in `xlsynth-crate`
> Implement from_verilog, tieoff, and port slice connections

- src/lib.rs
- tests/test.rs
TODO in future PRs:
* Validate actions: connect(), unused(), tieoff(), etc. Although everything is checked when validate() runs, this will make it easier to catch bugs, since many issues will be caught earlier.
* Make validation more efficient (more efficient checking of individual bits in ports, review cloning)
* Clean up EmitConfig usage - revist name for the enum and its variants and make it easier to specify the variant to use when creating new modules.
* General clean up of the implementation (this PR focused on user-facing functionality)
> First-pass implementation of the validate() method

- examples/demo.rs
- src/lib.rs
- tests/test.rs
* `EmitConfig` is renamed `Usage` to capture its more general meaning. Variant names are updated as well.
* The `pipeline` argument to `connect()` is removed for now.
* Added `ModDef.emit_to_file()` and `ModDef.from_verilog_file()` to simplify reading and writing files.
* Error messages are improved.
> API improvements

- examples/demo.rs
- src/lib.rs
- tests/test.rs
Avoids the need for this pattern that spreading in the test cases:
```rust
moddef.core.borrow_mut().usage = Usage::EmitStubAndStop;
```
> Specify usage in ModDef::new

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- examples/demo.rs
- examples/tb/demo.sh
- src/lib.rs
- tests/test.rs
API changes:
* `from_verilog*` methods now have an additional argument, `skip_unsupported`. If `true`, ports that use features not yet supported by TopStitch (`struct`, `enum`, `union`, etc.) are simply skipped in the port list, rather than resulting in an error.
* TopStitch output no longer includes sources provided to it for import; it only emits Verilog that it has generated.
> Use the latest version of slang-rs

- Cargo.lock
- Cargo.toml
- examples/demo.rs
- src/lib.rs
- tests/test.rs
Also implicitly convert to BigInt if needed when tying off interfaces.
> Allow validation to be disabled for prototyping

- Cargo.lock
- Cargo.toml
- examples/demo.rs
- src/lib.rs
- tests/test.rs
Makes the instance name optional in `instantiate()`, defaulting to the module name with `_inst` appended.
Also adds a method `instantiate_array` that can generate a multidimensional array of instances.
> Default instance name + instance arrays

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
Small method that makes it easier to connect two-port interfaces. May be expanded in the future.
> Add crossover() method

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
There was a bug where exporting a subdivided interface resulted in an error when the exported port was used later. The problem had to do with subdivided sections of buses `msb:lsb` with a non-zero `lsb` - that non-zero offset was incorrectly being used as the starting point for the exported port slice. This is problematic because the port has indices running from `0` to `msb-lsb+1`, not `lsb` to `msb`. As a result, when the port slice is used later, the check that `msb` is less than the port width fails.
The fix for this bug is one line, however I am also adding a test to check for this in the future, hence the ~100 LOC PR.
> Fix bug in exporting a subdivided interface

- Cargo.lock
- Cargo.toml
- rustfmt.toml
- src/lib.rs
- tests/test.rs
All public methods / structs / enums now have a rustdoc comment. Public visibility is also trimmed down a bit just to methods that need to be exposed.
> Add documentation for the public API

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
New function for `Port`/`PortSlice`:
* `export()`: Export a signal while keeping the same port name.
New functions for `Intf`:
* `export()`: Export a signal while keeping signals the same, under an interface with the same name.
* `export_with_name_underscore(name)`: Shorthand for `export_with_prefix("<name>", "<name>_")`
New functions for `ModDef`:
* `def_intf_from_name_underscore(name)`: Shorthand for `def_intf_from_prefix("<name>", "<name>_")` 
* `def_intf_from_prefixes(name, prefixes, strip_prefix)`: Gather multiple prefixes under a single interface with one command. `strip_prefix` controls whether the matching prefix should be stripped when inferring function names.
Updated `crossover` function: regex expression can now contain zero or more capture groups, which are joined with `_` to …
> Usability updates

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
PR contains a variety of experimental features to be refined (including documentation) in subsequent releases:
* Defining interfaces with search/replace regexes
* "Funnel" concept for feeding one or more interfaces through generic flat ports.
* Copy and flip operations for creating interfaces on one module definition that match or complement an existing interface. Like `export`, except no connectivity is established.
> Regex interface definition, funnel concept, copy/flip interface operations

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
This PR adds a method that applies `Usage::EmitStubAndStop` to instances within a `ModDef` whose names match a regular expression, descending recursively into their instances. Also as part of this PR, several access methods are added that make it possible to implement this sort of algorithm in TopStitch user code.
> Add stub_recursive and related methods

- Cargo.lock
- Cargo.toml
- src/inout.rs
- src/lib.rs
- tests/test.rs
Adds temporary support for `inout` ports by post-processing the generated netlist. `inout` ports are emitted with direction `input` by VAST, and they are given a special suffix, `_RENAME_INOUT`. Post-processing removes this suffix and changes `input` to `inout`. This will hopefully be replaced soon with a VAST API call.
The other key change required was to support direct connections from module definitions to module instances, without using an intermediate `assign`. This is important because `assign` cannot be used with `inout` in synthesizable code.
`inout` connections are not yet validated - this will be the subject of a future PR.
> Temporary support for inout

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
Previously, `incdirs` were not "remembered" when `parameterize()` was caused, which could cause parsing errors at that point.
> Use incdirs if provided when re-parsing modules given non-default parameters

- Cargo.lock
- Cargo.toml
- src/enum_type.rs
- src/lib.rs
- tests/test.rs
This PR deals with a specific LRM issue, which is that it is not legal to connect a non-arrayed enum input port directly to a flat bus. Instead, a cast must be used. This is not necessary for output ports or arrayed enum inputs.
This fix is temporary in two senses:
1. It is implemented with text parsing outside of VAST (would like to use VAST instead)
2. This problem should go away altogether when TopStitch has more direct support of enums, since there will no longer be a need to directly connect enums to flat buses.
> Cast for non-arrayed enum input ports

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
This PR fixes a bug where enum-related casting was not applied properly to modules with parameterization. Casting was not used in the wrapper for parameterization, where casting was needed, while casting was used in modules that instantiated the wrapper, where it should not have been used.
> Fix issue with enum ports and parameterization

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
In other words, rather than connecting a module port to a wire, and then assigning a constant to that wire, connect the module port to a constant.
Only applies to tieoffs on module instances.
> Implement whole-port tieoffs directly in instantiation

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/pipeline.rs
- tests/test.rs
This feature will be developed further in future PRs. For now only one type of pipeline module is instantiated, the `br_delay_nr` module from [bedrock-rtl](https://github.com/xlsynth/bedrock-rtl).
> Add feature for pipelining connections (including feedthroughs) + improve error messages

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/pipeline.rs
- tests/test.rs
Even though the `rst` input isn't connected within `br_delay_nr`, some tools may complain about it not being connected. For a similar reason `out_stages` is marked as unconnected with `.out_stages()`.
> Connect `rst` and `out_stages` on `br_delay_nr`

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
This PR adds several `InOut`-related features+related tests in a rough fashion, to be cleaned up in a future PR.
* Allow connections between `InOut` ports on modules
* Allow `Input`/`Output` ports to connect to `InOut` ports
* Check for unconnected `InOut` ports (they can now be marked `unused()`)
Note: direct connection (as opposed to assign-based connection) is being developed for `InOut`-related connections and will eventually replace `assign`-based connections in most places. That update is still a little while off, however - will involve updating most tests and consolidating a bunch of logic.
> `InOut` updates

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
This PR adds an alternative method for making connections, called `connect_to_net()`. Rather than `connect()`-ing inputs and outputs, ports and port slices are connected to nets with a given string name. Although less convenient than existing connection methods, this allows for direct control over wire net names used, and also avoids `assign` statements.
Also as part of this PR, the recently-added `set_wire_name()` method is removed. The reason is that `connect_to_net()` is both more powerful and easier to use.
> Add `connect_to_net()` and remove `set_wire_name()`

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
* Update the behavior of `crossover_through` and its variants so that port names flip at every interface, as opposed to only at the endpoints of the crossover connection. This means that, for example, if we are crossing over `data_out` to `data_in` through multiple instances, the instances where feedthroughs are punched will have `data_in` and `data_out` ports with the expected directionality. While the logical connectivity is the same as before, the port naming is much easier to interpret (and arguably more correct).
* `copy_to_with_prefix()` and `copy_to_with_name_underscore()` methods for copying an interface to a module definition with more control over the naming.
* More descriptive error messages for generated net name collisions, including suggestions on how to fix the errors. …
> More usability updates

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
Preprocessor defines were being ignored when re-running the parser on the parameterized version of a module.
Also in this PR: a fix for a bug in `copy_to` methods relating to the treatment of port slices.
> Fix issue with preprocessor define and `parameterize()` being used together

- Cargo.lock
- Cargo.toml
- src/lib.rs
In some cases, slang cannot infer the top-level module without it being
explicitly provided. The `parameterize` function doesn't do this, which
causes issues when reparsing. Pass the module name explciitly in `tops`
to solve this.
> Pass top-level module name explicitly to slang when reparameterizing module

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/test.rs
`PipelineConfig` now has an optional argument `inst_name` that specifies the instance name of the pipeline module used for a pipelined connection.
> Add option to name pipeline module instances

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .pre-commit-config.yaml
- .rustfmt.toml
- Cargo.lock
- Cargo.toml
- README.md
- check_version_is.py
- examples/tb/demo.sh
- src/mod_def/emit.rs
- tests/spdx_test.rs
- tests/version_test.rs
These are adapted from [xlsynth-crate](https://github.com/xlsynth/xlsynth-crate) and [bedrock-rtl](https://github.com/xlsynth/bedrock-rtl):
* Automatically publish to [crates.io](https://crates.io) when a `v*` tag is pushed.
* Check to make sure the `Cargo.toml` version is ahead of the crates.io version
* Check to make sure that there is an SPDX license comment at the top of each page
* Run pre-commit checks to catch file formatting issues.
> Add publish action + various checks

- src/mod_def.rs
- src/mod_def/abutment.rs
- src/mod_def/core.rs
- src/mod_def/parameterize.rs
- src/mod_def/parser.rs
- src/mod_def/stub.rs
- src/mod_inst.rs
- src/port_slice.rs
- tests/checks/abutment.rs
- tests/checks/mod.rs
- tests/spdx_test.rs
- tests/version_test.rs
This PR adds a basic feature for checking abutted connectivity. Module instances can be marked as adjacent to other module instances using the new `.mark_adjacent_to(other)` method, and a new method `.find_non_abutted_connections()` for is provided to retrieve a list of all connections within a module definition that cannot be made by abutment according to these annotations. Instances can be excluded from abutment checking with the method `.ignore_adjacency()`.
For now, the only connections analyzed are between module instances within a module definition. In the future, the analysis will be extended to examine connections hierarchically. This change will go well with other updates planned for the internal representation of connections.
Also includes an unrelated change to resolve a few …
> Add features for checking abutted connectivity

- .github/workflows/publish.yml
`cargo publish` errors out due to this file; seems better to remove the file rather than use `--allow-dirty`.
> Remove the `slang` binary before `cargo publish`

- Cargo.lock
- Cargo.toml
- src/intf/connect.rs
- src/intf/crossover.rs
- src/mod_def/abutment.rs
- src/mod_def/dtypes.rs
- src/mod_def/emit.rs
- src/mod_def/feedthrough.rs
- src/mod_def/validate.rs
- src/port/connect.rs
- src/port_slice/connect.rs
- src/port_slice/feedthrough.rs
- tests/checks/abutment.rs
* Connections involving `ModDef` ports are skipped, rather than causing an error. This is sensible because adjacency between a `ModDef` and a `ModInst` is not defined. In the future, we can treat these types of connections more accurately by analyzing connections hierarchically.
* `connect` and `crossover` now have `_non_abutted` variants that indicate that certain connections are intended to be non-abutted.
> Updates to the abutment checking feature

- .pre-commit-config.yaml
- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/mod_def.rs
- src/mod_def/hierarchy.rs
- src/mod_def/parameterize.rs
- src/mod_def/parser.rs
- src/mod_def/parser_cfg.rs
- src/package.rs
- tests/hierarchy.rs
- tests/package.rs
- tests/syntax/import.rs
- tests/syntax/params.rs
To parse hierarchical contents when importing Verilog, set `include_hierarchy=true` in `ParserConfig`. The `ModDef` returned by TopStitch will then contain module instances, the module definitions for those instances will in turn contain module instances, etc. as far down as the real Verilog hierarchy goes. A convenience method `ModDef.report_all_instances` is provided that returns a vector of definition name / instance name tuples that can be used in downstream processing. More customized processing can always be implemented by working with `ModDef` and `ModInst` structs directly.
SystemVerilog `package` support is provided with the `extract_packages_*` functions; all return a mapping that can be used to retrieve parameter values by package name and parameter name.
To support these …
> Initial support for parsing hierarchies + `package` support

- Cargo.lock
- Cargo.toml
- src/mod_def/hierarchy.rs
- src/mod_def/parser.rs
- tests/hierarchy.rs
This was problematic because it meant that different parameterizations of the same module had the same hierarchy, which is not always the case. Could revisit caching in the future as a performance optimization.
> Remove caching from hierarchy extraction

- Cargo.lock
- Cargo.toml
- src/funnel.rs
- tests/feedthroughs/funnel.rs
Adds new functions `a2b_yield_remaining` and `b2a_yield_remaining`; gives `done` the more descriptive name `tieoff_remaining`. In the future, this "yield" mechanism could be generalized to yield a certain number of bits or error out, avoiding a duplication of logic.
> Update mechanism for working with remaining funnel capacity

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/mod_def.rs
- src/mod_def/core.rs
- src/mod_def/parameterize.rs
- src/mod_def/parser.rs
- src/mod_def/stub.rs
- tests/syntax/params.rs
This pulls in changes from slang-rs that lets us extract parameter definitions from the SV file. Add a 'parameters' member to the module definition that keeps the parameter definitions. Then, when parameterizing, check these definitions to determine the width of the literals that should be passed to slang and xlsynth.
> Allow ModDef::parameterize to take values larger than 32 bits

- Cargo.lock
- Cargo.toml
- src/mod_def.rs
- src/mod_def/core.rs
- src/mod_def/parameterize.rs
- src/mod_def/parser.rs
- src/mod_def/stub.rs
- tests/syntax/params.rs
The previous way of handling parameters would have an issue if the width
of one parameter depended on another, since the parameter types were
only parsed during loading of the original unparameterized module.
Remove the parameters field from ModDefCore and instead derive
the parameter types on demand when the module is re-parsed
with the new parameter values.
---
**Stack**:
- #96
- #95 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> Fix handling of parameters with dependent widths

- Cargo.lock
- Cargo.toml
- src/lefdef.rs
- src/lib.rs
- src/mod_def.rs
- src/mod_def/core.rs
- src/mod_def/dtypes.rs
- src/mod_def/lefdef.rs
- src/mod_def/parameterize.rs
- src/mod_def/parser.rs
- src/mod_def/parser_cfg.rs
- src/mod_def/placement.rs
- src/mod_def/stub.rs
- src/mod_inst.rs
- src/usage.rs
- tests/emit_lefdef.rs
- tests/lefdef_gen.rs
- tests/placement.rs
**Overview**
- **APIs:** Adds `ModDef::emit_lef_def(opts)` to return LEF/DEF strings and `ModDef::emit_lef_def_to_files(lef_path, def_path, opts)` to write them to disk.
- **Traversal:** Uses `Usage` to control descent. Modules marked `EmitStubAndStop` or `EmitDefinitionAndStop` act as leaves for physical design; they produce a LEF macro (from their shape) and DEF component placements (from instance placements). This is an extension of the current meaning of `Usage`, which indicates leaves for logical design. In the future, DEF might be used to represent leaves, but for now this is a convenient way to create empty boxes and view placements with KLayout.
**Shaping and Placement**
- **`ModDef`:** `set_width_height(w, h)` and `set_shape(RectilinearShape)` define leaf geometry. …
> Basic features for placement

- Cargo.lock
- Cargo.toml
- examples/pinning.rs
- src/lefdef.rs
- src/lib.rs
- src/mod_def.rs
- src/mod_def/core.rs
- src/mod_def/dtypes.rs
- src/mod_def/lefdef.rs
- src/mod_def/parameterize.rs
- src/mod_def/parser.rs
- src/mod_def/pins.rs
- src/mod_def/placement.rs
- src/mod_def/stub.rs
- tests/lef_pins.rs
- tests/lefdef_gen.rs
- tests/placement.rs
This PR adds general (but very low-level) support for pinning. The basic low-level operation is to take a bit in a `ModDef` `Port` and give it:
1. A layer (`String`)
2. A position (`Coordinate`)
3. A shape (`Polygon`)
When LEFs are generated, they include this information.
This PR does not contain any notion of tracks, bus-level placement, connectivity-driven pinning, etc. These higher-level features will be explored in future PRs, and will build off the low-level pinning feature in this PR.
For an example of low-level pinning, see `examples/pinning.rs`, which produces the following layout:
> Low-level pinning features

- Cargo.lock
- Cargo.toml
- examples/pin_range_example.rs
- examples/pinning.rs
- src/lefdef.rs
- src/lib.rs
- src/mod_def.rs
- src/mod_def/dtypes.rs
- src/mod_def/lefdef.rs
- src/mod_def/pins.rs
- src/mod_def/tracks.rs
Previously, the pin spread algorithm constrained pins to be a minimum spacing apart, and ran a binary search on the minimum spacing. Now, the algorithm checks that pin placement positions lie above an "index-on-layer vs. position" line, and runs a binary search on the slope of that line. This helps to avoid quantization issues that prevented pins from being placed all the way to the edge of a range.
(This PR also includes some unrelated cleanup of clippy warnings.)
> Update pin spread algorithm
